apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vito-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/vitocodepython/app-ci-cd.git'
    targetRevision: main
    path: manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
